// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://musicfun.it-incubator.app/api/1.0' | (string & {});
};

export type UserRef = {
    /**
     * Unique identifier of the user
     */
    id: string;
    /**
     * Name of the user
     */
    name: string;
};

/**
 * Type of the image size (e.g., original, thumbnail variants)
 */
export type ImageSizeType = 'original' | 'thumbnail' | 'medium';

export type ImageVariant = {
    /**
     * Type of the image size (e.g., original, thumbnail variants)
     */
    type: ImageSizeType;
    /**
     * Image width in pixels
     */
    width: number;
    /**
     * Image height in pixels
     */
    height: number;
    /**
     * Image file size in bytes
     */
    fileSize: number;
    /**
     * Full public URL of the image
     */
    url: string;
};

export type PlaylistImagesOutputDto = {
    /**
     * Original images and thumbnail previews
     */
    main?: Array<ImageVariant>;
};

export type TagRef = {
    /**
     * Unique identifier of the tag
     */
    id: string;
    /**
     * Original name of the tag
     */
    name: string;
};

/**
 * User reaction: 0 – guest or no reaction; 1 – like; -1 – dislike
 */
export type ReactionValue = 0 | 1 | -1;

export type PlaylistListItemAttributes = {
    /**
     * Title of the playlist
     */
    title: string;
    /**
     * Date and time when the playlist was added (ISO 8601)
     */
    addedAt: string;
    /**
     * Date and time when the playlist was last updated (ISO 8601)
     */
    updatedAt: string;
    /**
     * Order index of the playlist
     */
    order: number;
    /**
     * User who created the playlist
     */
    user: UserRef;
    /**
     * Images associated with the playlist
     */
    images: PlaylistImagesOutputDto;
    /**
     * Tags linked to the playlist
     */
    tags: Array<TagRef>;
    /**
     * Total number of likes for this playlist
     */
    likesCount: number;
    /**
     * Total number of dislikes for this playlist
     */
    dislikesCount: number;
    /**
     * User reaction: 0 – guest or no reaction; 1 – like; -1 – dislike
     */
    currentUserReaction: ReactionValue;
    /**
     * Total number of tracks in the playlist
     */
    tracksCount: number;
    /**
     * Total duration of the playlist in seconds
     */
    duration: number;
};

export type PlaylistListItemResource = {
    /**
     * Unique identifier of the playlist
     */
    id: string;
    /**
     * Resource type (should be "playlists")
     */
    type: string;
    attributes: PlaylistListItemAttributes;
};

export type GetMyPlaylistsOutput = {
    /**
     * Array of playlist resource objects owned by the current user
     */
    data: Array<PlaylistListItemResource>;
};

export type CreatePlaylistAttributes = {
    /**
     * Playlist title (1 to 100 characters)
     */
    title: string;
    /**
     * Playlist description (up to 1000 characters)
     */
    description: string | null;
};

export type CreatePlaylistData = {
    type: string;
    attributes: CreatePlaylistAttributes;
};

export type CreatePlaylistRequestPayload = {
    data: CreatePlaylistData;
};

export type PlaylistAttributes = {
    /**
     * Title of the playlist
     */
    title: string;
    /**
     * Description of the playlist
     */
    description: string | null;
    /**
     * Date and time when the playlist was added (ISO 8601)
     */
    addedAt: string;
    /**
     * Date and time when the playlist was last updated (ISO 8601)
     */
    updatedAt: string;
    /**
     * Order index of the playlist
     */
    order: number;
    /**
     * User who created the playlist
     */
    user: UserRef;
    /**
     * Images associated with the playlist
     */
    images: PlaylistImagesOutputDto;
    /**
     * Tags linked to the playlist
     */
    tags: Array<TagRef>;
    /**
     * Total number of likes for this playlist
     */
    likesCount: number;
    /**
     * Total number of dislikes for this playlist
     */
    dislikesCount: number;
    /**
     * User reaction: 0 – guest or no reaction; 1 – like; -1 – dislike
     */
    currentUserReaction: ReactionValue;
    /**
     * Total number of tracks in the playlist
     */
    tracksCount: number;
    /**
     * Total duration of the playlist in seconds
     */
    duration: number;
};

export type PlaylistResource = {
    /**
     * Unique identifier of the playlist
     */
    id: string;
    /**
     * Resource type (should be "playlists")
     */
    type: string;
    attributes: PlaylistAttributes;
};

export type GetPlaylistOutput = {
    data: PlaylistResource;
};

export type UpdatePlaylistAttributes = {
    /**
     * Playlist title (1 – 100 characters)
     */
    title: string;
    /**
     * Playlist description (up to 1000 characters)
     */
    description: string | null;
    /**
     * Tag IDs to associate with the playlist (0 – 5 items; [] = clear tags)
     */
    tagIds: Array<string>;
};

export type UpdatePlaylistData = {
    type: string;
    attributes: UpdatePlaylistAttributes;
};

export type UpdatePlaylistRequestPayload = {
    data: UpdatePlaylistData;
};

export type ReorderPlaylistsRequestPayload = {
    /**
     * ID of the playlist after which the current playlist should be inserted. Send null to place the playlist at the beginning of the list.
     */
    putAfterItemId: string | null;
};

export type TrackImages = {
    /**
     * List of original images and thumbnail versions (e.g., original, 320x180, etc.)
     */
    main?: Array<ImageVariant>;
};

export type GetTracksRequestPayload = {
    /**
     * Page number for pagination (starting from 1)
     */
    pageNumber?: number;
    /**
     * Page size for pagination (between 0 and 20)
     */
    pageSize?: number;
    /**
     * Search term for filtering playlists by name
     */
    search?: string;
    /**
     * Field by which to sort tracks
     */
    sortBy?: 'publishedAt' | 'likesCount';
    /**
     * Sort direction (ascending or descending)
     */
    sortDirection?: 'asc' | 'desc';
    /**
     * Filter by tag IDs (multiple values allowed)
     */
    tagsIds?: Array<string>;
    /**
     * Filter by artist IDs (multiple values allowed)
     */
    artistsIds?: Array<string>;
    /**
     * Filter by user ID (track creator's ID)
     */
    userId?: string;
    /**
     * If true, include unpublished tracks (drafts) of current user if userId === currentUserId
     */
    includeDrafts?: boolean;
    /**
     * If true, return only tracks liked by the current authenticated user
     */
    onlyLikedByMe?: boolean;
    /**
     * Pagination type: "offset" for page-number pagination; "cursor" for keyset/seek-based pagination.
     */
    paginationType?: 'offset' | 'cursor';
    /**
     * Base64-encoded cursor for keyset pagination. Used only if paginationType is "cursor".
     */
    cursor?: string | null;
};

export type JsonApiErrorSource = {
    /**
     * e.g. "/data/attributes/field"
     */
    pointer?: string;
    /**
     * e.g. "?queryParam"
     */
    parameter?: string;
};

export type JsonApiError = {
    /**
     * HTTP status code as a string
     */
    status: string;
    /**
     * Application-specific error code
     */
    code?: {
        [key: string]: unknown;
    };
    /**
     * Short, human-readable summary
     */
    title?: string;
    /**
     * Detailed explanation
     */
    detail?: string;
    /**
     * Pointer to the associated entity in the request
     */
    source?: JsonApiErrorSource;
    /**
     * Any extra data
     */
    meta?: {
        [key: string]: unknown;
    };
};

export type JsonApiErrorDocument = {
    /**
     * Array of one or more errors
     */
    errors: Array<JsonApiError>;
    /**
     * e.g. timestamp, path, traceId, etc.
     */
    meta?: {
        [key: string]: unknown;
    };
};

export type TrackAttachment = {
    /**
     * Unique identifier of the entity
     */
    id: string;
    /**
     * Date and time when the entity was added
     */
    addedAt: string;
    /**
     * Date and time when the entity was last updated
     */
    updatedAt: string;
    /**
     * Version number of the entity (for concurrency control)
     */
    version: number;
    /**
     * Public URL to access the uploaded file
     */
    url: string;
    /**
     * MIME type of the file
     */
    contentType: string;
    /**
     * Original filename uploaded by the user
     */
    originalName: string;
    /**
     * Size of the file in bytes
     */
    fileSize: number;
};

export type TrackListItemAttributes = {
    title: string;
    /**
     * Date and time when the track was added (ISO 8601)
     */
    addedAt: string;
    likesCount: number;
    attachments: Array<TrackAttachment>;
    images: TrackImages;
    user: UserRef;
    /**
     * 0 – не залогинен или не реагировал; 1 – лайк; −1 – дизлайк
     */
    currentUserReaction: 0 | 1 | -1;
    isPublished: boolean;
    /**
     * Date and time when the track was published (ISO 8601)
     */
    publishedAt?: string | null;
    /**
     * Duration of the track in seconds
     */
    duration: number;
};

export type ArtistRelationship = {
    id: string;
    type: string;
};

export type ArtistsRelationship = {
    data: Array<ArtistRelationship>;
};

export type TrackRelationships = {
    artists: ArtistsRelationship;
};

export type TrackListItemResource = {
    id: string;
    type: string;
    attributes: TrackListItemAttributes;
    relationships: TrackRelationships;
};

export type JsonApiMetaWithPagingAndCursor = {
    page: number;
    pageSize: number;
    /**
     * Total count may be absent when using keyset pagination
     */
    totalCount: number | null;
    /**
     * Total number of pages
     */
    pagesCount: number | null;
    /**
     * Cursor for the next page
     */
    nextCursor: string | null;
};

export type OmitTypeClass = {
    /**
     * Name of the artist
     */
    name: string;
};

export type IncludedArtistOutput = {
    id: string;
    type: string;
    attributes: OmitTypeClass;
};

export type GetTrackListOutput = {
    data: Array<TrackListItemResource>;
    meta: JsonApiMetaWithPagingAndCursor;
    included: Array<IncludedArtistOutput>;
};

export type TrackListItemAttributesForPlaylist = {
    /**
     * Title of the track
     */
    title: string;
    /**
     * Order index of the track in the playlist
     */
    order: number;
    /**
     * Date and time when the track was added (ISO 8601)
     */
    addedAt: string;
    /**
     * Date and time when the track was last updated (ISO 8601)
     */
    updatedAt: string;
    /**
     * Attachments related to the track
     */
    attachments: Array<TrackAttachment>;
    /**
     * Images associated with the track
     */
    images: TrackImages;
    /**
     * User reaction: 0 – guest or no reaction; 1 – liked; -1 – disliked
     */
    currentUserReaction: 0 | 1 | -1;
    /**
     * Date and time when the track was published (ISO 8601)
     */
    publishedAt?: string | null;
    /**
     * Duration of the track in seconds
     */
    duration: number;
};

export type TrackListItemResourceForPlaylist = {
    id: string;
    type: string;
    attributes: TrackListItemAttributesForPlaylist;
    relationships: TrackRelationships;
};

export type JsonApiMeta = {
    totalCount: number;
};

export type GetTracksForPlaylistOutput = {
    data: Array<TrackListItemResourceForPlaylist>;
    meta: JsonApiMeta;
    included: Array<IncludedArtistOutput>;
};

export type ArtistRef = {
    /**
     * Unique identifier of the artist
     */
    id: string;
    /**
     * Name of the artist
     */
    name: string;
};

export type TrackDetailsAttributes = {
    /**
     * Track title
     */
    title: string;
    /**
     * Track lyrics text
     */
    lyrics?: string | null;
    /**
     * Release date in ISO 8601 format
     */
    releaseDate?: string | null;
    /**
     * Date and time when the track was added (ISO 8601)
     */
    addedAt: string;
    /**
     * Date and time when the track was last updated (ISO 8601)
     */
    updatedAt: string;
    /**
     * Duration of the track in seconds
     */
    duration: number;
    /**
     * Total number of likes for this track
     */
    likesCount: number;
    /**
     * Total number of dislikes for this track
     *
     * @deprecated
     */
    dislikesCount: number;
    /**
     * List of attachments related to the track
     */
    attachments: Array<TrackAttachment>;
    images: TrackImages;
    /**
     * Tags associated with the track
     */
    tags: Array<TagRef>;
    /**
     * Artists associated with the track
     */
    artists: Array<ArtistRef>;
    user: UserRef;
    /**
     * Publication status of the track
     */
    isPublished: boolean;
    /**
     * Publication date in ISO 8601 format
     */
    publishedAt?: string | null;
    /**
     * User reaction: 0 – guest or no reaction; 1 – user liked; -1 – user disliked
     */
    currentUserReaction: 0 | 1 | -1;
};

export type TrackDetailsResource = {
    /**
     * Unique identifier of the track
     */
    id: string;
    /**
     * Resource type (should be "tracks")
     */
    type: string;
    attributes: TrackDetailsAttributes;
};

export type GetTrackDetailsOutput = {
    data: TrackDetailsResource;
};

export type ReactionOutput = {
    objectId: string;
    value: 0 | 1 | -1;
    likes: number;
    dislikes: number;
};

export type GetPlaylistsRequestPayload = {
    /**
     * Page number for pagination (starting from 1)
     */
    pageNumber?: number;
    /**
     * Page size for pagination (between 0 and 20)
     */
    pageSize?: number;
    /**
     * Search term for filtering playlists by name
     */
    search?: string;
    /**
     * Field by which to sort playlists
     */
    sortBy?: 'addedAt' | 'likesCount';
    /**
     * Sort direction (ascending or descending)
     */
    sortDirection?: 'asc' | 'desc';
    /**
     * Filter by tag IDs. Multiple values allowed, e.g.: tagsIds=tag1&tagsIds=tag2
     */
    tagsIds?: Array<string>;
    /**
     * Filter by user ID (playlist creator’s ID)
     */
    userId?: string;
    /**
     * Filter by track ID – only playlists containing this track will be returned
     */
    trackId?: string;
    /**
     * If true, return only playlists liked by the current authenticated user
     */
    onlyLikedByMe?: boolean;
};

export type JsonApiMetaWithPaging = {
    totalCount: number;
    page: number;
    pageSize: number;
    pagesCount: number;
};

export type GetPlaylistsOutput = {
    /**
     * Array of playlist resource objects
     */
    data: Array<PlaylistListItemResource>;
    meta: JsonApiMetaWithPaging;
};

export type ReorderTracksRequestPayload = {
    /**
     * ID of the track after which the current track should be inserted. Send null to place the track at the beginning of the list.
     */
    putAfterItemId: string | null;
};

export type UpdateTrackAttributes = {
    /**
     * Track title (1 to 100 characters)
     */
    title: string;
    /**
     * Track lyrics (up to 5000 characters)
     */
    lyrics: string | null;
    /**
     * Release date in ISO 8601 format
     */
    releaseDate: string | null;
    /**
     * Array of tag IDs to associate with the track (up to 5)
     */
    tagIds: Array<string>;
    /**
     * Array of artist IDs to associate with the track (up to 5)
     */
    artistsIds: Array<string>;
};

export type UpdateTrackData = {
    type: string;
    attributes: UpdateTrackAttributes;
};

export type UpdateTrackRequestPayload = {
    data: UpdateTrackData;
};

export type AddTrackToPlaylistAttributes = {
    /**
     * ID of the track to add to the playlist
     */
    trackId: string;
};

export type AddTrackToPlaylistData = {
    type: string;
    attributes: AddTrackToPlaylistAttributes;
};

export type AddTrackToPlaylistRequestPayload = {
    data: AddTrackToPlaylistData;
};

export type CreateArtistAttributes = {
    /**
     * Artist name (must be between 2 and 30 characters)
     */
    name: string;
};

export type CreateArtistData = {
    type: string;
    attributes: CreateArtistAttributes;
};

export type CreateArtistRequestPayload = {
    data: CreateArtistData;
};

export type LoginRequestPayload = {
    /**
     * Authorization code received from OAuth server after redirect
     */
    code: string;
    /**
     * Specify the same redirect URI used in the initial OAuth server request
     */
    redirectUri: string;
    /**
     * Access token lifetime (default "3m"); must be a string like "60s", "3m", "2h", or "1d"
     */
    accessTokenTTL?: string;
    /**
     * Refresh token lifetime: if true, 30 days; if false, 30 minutes. accessTokenTTL must not exceed the refresh token lifetime
     */
    rememberMe: boolean;
};

export type RefreshOutput = {
    refreshToken: string;
    accessToken: string;
};

export type BadRequestException = {
    [key: string]: unknown;
};

export type UnauthorizedException = {
    [key: string]: unknown;
};

export type RefreshRequestPayload = {
    refreshToken: string;
};

export type LogoutRequestPayload = {
    refreshToken: string;
};

export type GetMeOutput = {
    userId: string;
    login: string;
};

export type SimpleLoginRequestPayload = {
    /**
     * User login
     */
    login: string;
    /**
     * User password
     */
    password: string;
    /**
     * Refresh token lifetime: if true, 7 days; if false, 30 minutes
     */
    rememberMe: boolean;
};

export type SimpleLoginOutput = {
    accessToken: string;
    refreshToken: string;
};

export type SimpleRefreshRequestPayload = {
    /**
     * Refresh token
     */
    refreshToken: string;
};

export type SimpleLogoutRequestPayload = {
    /**
     * Refresh token to invalidate
     */
    refreshToken: string;
};

export type CreateTagAttributes = {
    /**
     * Tag name (2 to 30 characters)
     */
    name: string;
};

export type CreateTagData = {
    type: string;
    attributes: CreateTagAttributes;
};

export type CreateTagRequestPayload = {
    data: CreateTagData;
};

export type TagAttributes = {
    /**
     * Original name of the tag
     */
    name: string;
};

export type TagResource = {
    /**
     * Unique identifier of the tag
     */
    id: string;
    /**
     * Resource type (should be "tags")
     */
    type: string;
    attributes: TagAttributes;
};

export type GetTagOutput = {
    data: TagResource;
};

export type GetTagsOutput = {
    /**
     * Array of tag resource objects
     */
    data: Array<TagResource>;
};

/**
 * Файл в multipart/form-data
 */
export type BinaryFile = Blob | File;

export type PlaylistsControllerGetMyPlaylistsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/playlists/my';
};

export type PlaylistsControllerGetMyPlaylistsErrors = {
    /**
     * Unauthorized: User not authenticated
     */
    401: unknown;
};

export type PlaylistsControllerGetMyPlaylistsResponses = {
    /**
     * OK: List of playlists retrieved successfully
     */
    200: GetMyPlaylistsOutput;
};

export type PlaylistsControllerGetMyPlaylistsResponse = PlaylistsControllerGetMyPlaylistsResponses[keyof PlaylistsControllerGetMyPlaylistsResponses];

export type PlaylistsPublicControllerGetPlaylistsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page number for pagination (starting from 1)
         */
        pageNumber?: number;
        /**
         * Page size for pagination (between 0 and 20)
         */
        pageSize?: number;
        /**
         * Search term for filtering playlists by name
         */
        search?: string;
        /**
         * Field by which to sort playlists
         */
        sortBy?: 'addedAt' | 'likesCount';
        /**
         * Sort direction (ascending or descending)
         */
        sortDirection?: 'asc' | 'desc';
        /**
         * Filter by tag IDs. Multiple values allowed, e.g.: tagsIds=tag1&tagsIds=tag2
         */
        tagsIds?: Array<string>;
        /**
         * Filter by user ID (playlist creator’s ID)
         */
        userId?: string;
        /**
         * Filter by track ID – only playlists containing this track will be returned
         */
        trackId?: string;
        /**
         * If true, return only playlists liked by the current authenticated user
         */
        onlyLikedByMe?: boolean;
    };
    url: '/playlists';
};

export type PlaylistsPublicControllerGetPlaylistsResponses = {
    /**
     * OK: JSON:API list of playlists with pagination
     */
    200: GetPlaylistsOutput;
};

export type PlaylistsPublicControllerGetPlaylistsResponse = PlaylistsPublicControllerGetPlaylistsResponses[keyof PlaylistsPublicControllerGetPlaylistsResponses];

export type PlaylistsControllerCreatePlaylistData = {
    body: CreatePlaylistRequestPayload;
    path?: never;
    query?: never;
    url: '/playlists';
};

export type PlaylistsControllerCreatePlaylistErrors = {
    /**
     * Forbidden: Playlist creation limit exceeded
     */
    403: unknown;
};

export type PlaylistsControllerCreatePlaylistResponses = {
    /**
     * Created: Playlist created successfully
     */
    201: GetPlaylistOutput;
};

export type PlaylistsControllerCreatePlaylistResponse = PlaylistsControllerCreatePlaylistResponses[keyof PlaylistsControllerCreatePlaylistResponses];

export type PlaylistsControllerDeletePlaylistData = {
    body?: never;
    path: {
        playlistId: string;
    };
    query?: never;
    url: '/playlists/{playlistId}';
};

export type PlaylistsControllerDeletePlaylistErrors = {
    /**
     * Forbidden: Insufficient permissions to delete this playlist
     */
    403: unknown;
    /**
     * Not Found: Playlist not found
     */
    404: unknown;
};

export type PlaylistsControllerDeletePlaylistResponses = {
    /**
     * No Content: Playlist deleted successfully
     */
    204: void;
};

export type PlaylistsControllerDeletePlaylistResponse = PlaylistsControllerDeletePlaylistResponses[keyof PlaylistsControllerDeletePlaylistResponses];

export type PlaylistsPublicControllerGetPlaylistByIdData = {
    body?: never;
    path: {
        /**
         * ID of the playlist
         */
        playlistId: string;
    };
    query?: never;
    url: '/playlists/{playlistId}';
};

export type PlaylistsPublicControllerGetPlaylistByIdErrors = {
    /**
     * Not Found: Playlist with the given ID not found
     */
    404: unknown;
};

export type PlaylistsPublicControllerGetPlaylistByIdResponses = {
    /**
     * OK: Playlist retrieved successfully
     */
    200: GetPlaylistOutput;
};

export type PlaylistsPublicControllerGetPlaylistByIdResponse = PlaylistsPublicControllerGetPlaylistByIdResponses[keyof PlaylistsPublicControllerGetPlaylistByIdResponses];

export type PlaylistsControllerUpdatePlaylistData = {
    body: UpdatePlaylistRequestPayload;
    path: {
        playlistId: string;
    };
    query?: never;
    url: '/playlists/{playlistId}';
};

export type PlaylistsControllerUpdatePlaylistErrors = {
    /**
     * Bad Request: Validation error (e.g., tag limit exceeded)
     */
    400: unknown;
    /**
     * Forbidden: You do not have permission to update this playlist
     */
    403: unknown;
};

export type PlaylistsControllerUpdatePlaylistResponses = {
    /**
     * No Content: Playlist updated successfully
     */
    204: void;
};

export type PlaylistsControllerUpdatePlaylistResponse = PlaylistsControllerUpdatePlaylistResponses[keyof PlaylistsControllerUpdatePlaylistResponses];

export type PlaylistsControllerReorderPlaylistData = {
    body: ReorderPlaylistsRequestPayload;
    path: {
        playlistId: string;
    };
    query?: never;
    url: '/playlists/{playlistId}/reorder';
};

export type PlaylistsControllerReorderPlaylistErrors = {
    /**
     * Not Found: Playlist or putAfterItemId not found
     */
    404: unknown;
};

export type PlaylistsControllerReorderPlaylistResponses = {
    /**
     * No Content: Playlist order updated successfully
     */
    204: void;
};

export type PlaylistsControllerReorderPlaylistResponse = PlaylistsControllerReorderPlaylistResponses[keyof PlaylistsControllerReorderPlaylistResponses];

export type PlaylistsControllerDeleteTrackCoverData = {
    body?: never;
    path: {
        playlistId: string;
    };
    query?: never;
    url: '/playlists/{playlistId}/images/main';
};

export type PlaylistsControllerDeleteTrackCoverErrors = {
    /**
     * Forbidden: Removing another user’s playlist cover is not allowed
     */
    403: unknown;
    /**
     * Not Found: Playlist not found
     */
    404: unknown;
};

export type PlaylistsControllerDeleteTrackCoverResponses = {
    /**
     * No Content: Cover deleted successfully
     */
    204: void;
};

export type PlaylistsControllerDeleteTrackCoverResponse = PlaylistsControllerDeleteTrackCoverResponses[keyof PlaylistsControllerDeleteTrackCoverResponses];

export type PlaylistsControllerUploadMainImageData = {
    body: {
        file: BinaryFile;
    };
    path: {
        playlistId: string;
    };
    query?: never;
    url: '/playlists/{playlistId}/images/main';
};

export type PlaylistsControllerUploadMainImageErrors = {
    /**
     * Bad Request: Invalid image format or dimensions
     */
    400: unknown;
    /**
     * Forbidden: No permission to upload cover for this playlist
     */
    403: unknown;
};

export type PlaylistsControllerUploadMainImageResponses = {
    /**
     * OK: Cover uploaded successfully
     */
    200: TrackImages;
};

export type PlaylistsControllerUploadMainImageResponse = PlaylistsControllerUploadMainImageResponses[keyof PlaylistsControllerUploadMainImageResponses];

export type TracksPublicControllerGetAllTracksData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page number for pagination (starting from 1)
         */
        pageNumber?: number;
        /**
         * Page size for pagination (between 0 and 20)
         */
        pageSize?: number;
        /**
         * Search term for filtering playlists by name
         */
        search?: string;
        /**
         * Field by which to sort tracks
         */
        sortBy?: 'publishedAt' | 'likesCount';
        /**
         * Sort direction (ascending or descending)
         */
        sortDirection?: 'asc' | 'desc';
        /**
         * Filter by tag IDs (multiple values allowed)
         */
        tagsIds?: Array<string>;
        /**
         * Filter by artist IDs (multiple values allowed)
         */
        artistsIds?: Array<string>;
        /**
         * Filter by user ID (track creator's ID)
         */
        userId?: string;
        /**
         * If true, include unpublished tracks (drafts) of current user if userId === currentUserId
         */
        includeDrafts?: boolean;
        /**
         * If true, return only tracks liked by the current authenticated user
         */
        onlyLikedByMe?: boolean;
        /**
         * Pagination type: "offset" for page-number pagination; "cursor" for keyset/seek-based pagination.
         */
        paginationType?: 'offset' | 'cursor';
        /**
         * Base64-encoded cursor for keyset pagination. Used only if paginationType is "cursor".
         */
        cursor?: string | null;
    };
    url: '/playlists/tracks';
};

export type TracksPublicControllerGetAllTracksErrors = {
    /**
     * Bad Request: invalid query parameters
     */
    400: JsonApiErrorDocument;
};

export type TracksPublicControllerGetAllTracksError = TracksPublicControllerGetAllTracksErrors[keyof TracksPublicControllerGetAllTracksErrors];

export type TracksPublicControllerGetAllTracksResponses = {
    /**
     * OK: Paginated list of tracks
     */
    200: GetTrackListOutput;
};

export type TracksPublicControllerGetAllTracksResponse = TracksPublicControllerGetAllTracksResponses[keyof TracksPublicControllerGetAllTracksResponses];

export type TracksPublicControllerGetPlaylistTracksData = {
    body?: never;
    path: {
        /**
         * ID of the playlist to retrieve tracks for
         */
        playlistId: string;
    };
    query?: never;
    url: '/playlists/{playlistId}/tracks';
};

export type TracksPublicControllerGetPlaylistTracksErrors = {
    /**
     * Not Found: Playlist with the specified ID not found
     */
    404: unknown;
};

export type TracksPublicControllerGetPlaylistTracksResponses = {
    /**
     * OK: List of tracks in the playlist
     */
    200: GetTracksForPlaylistOutput;
};

export type TracksPublicControllerGetPlaylistTracksResponse = TracksPublicControllerGetPlaylistTracksResponses[keyof TracksPublicControllerGetPlaylistTracksResponses];

export type TracksControllerDeleteTrackCompletelyData = {
    body?: never;
    path: {
        trackId: string;
    };
    query?: never;
    url: '/playlists/tracks/{trackId}';
};

export type TracksControllerDeleteTrackCompletelyErrors = {
    /**
     * Forbidden: Deleting another user’s track is not allowed
     */
    403: unknown;
    /**
     * Not Found: Track not found
     */
    404: unknown;
};

export type TracksControllerDeleteTrackCompletelyResponses = {
    /**
     * No Content: Track permanently deleted
     */
    204: void;
};

export type TracksControllerDeleteTrackCompletelyResponse = TracksControllerDeleteTrackCompletelyResponses[keyof TracksControllerDeleteTrackCompletelyResponses];

export type TracksPublicControllerGetTrackDetailsData = {
    body?: never;
    path: {
        /**
         * ID of the track to retrieve details for
         */
        trackId: string;
    };
    query?: never;
    url: '/playlists/tracks/{trackId}';
};

export type TracksPublicControllerGetTrackDetailsErrors = {
    /**
     * Not Found: Track with the specified ID not found
     */
    404: unknown;
};

export type TracksPublicControllerGetTrackDetailsResponses = {
    /**
     * OK: Track details with attachments
     */
    200: GetTrackDetailsOutput;
};

export type TracksPublicControllerGetTrackDetailsResponse = TracksPublicControllerGetTrackDetailsResponses[keyof TracksPublicControllerGetTrackDetailsResponses];

export type TracksControllerUpdateTrackData = {
    body: UpdateTrackRequestPayload;
    path: {
        trackId: string;
    };
    query?: never;
    url: '/playlists/tracks/{trackId}';
};

export type TracksControllerUpdateTrackErrors = {
    /**
     * Bad Request: Tag or artist limit exceeded
     */
    400: unknown;
    /**
     * Forbidden: Editing another user’s track is not allowed
     */
    403: unknown;
    /**
     * Not Found: Track or playlist not found
     */
    404: unknown;
};

export type TracksControllerUpdateTrackResponses = {
    /**
     * OK: Track updated successfully
     */
    200: GetTrackDetailsOutput;
};

export type TracksControllerUpdateTrackResponse = TracksControllerUpdateTrackResponses[keyof TracksControllerUpdateTrackResponses];

export type TracksPublicControllerLikeTrackData = {
    body?: never;
    path: {
        trackId: string;
    };
    query?: never;
    url: '/playlists/tracks/{trackId}/likes';
};

export type TracksPublicControllerLikeTrackErrors = {
    /**
     * Bad Request: Invalid track ID
     */
    400: unknown;
    /**
     * Unauthorized: User not authenticated
     */
    401: unknown;
    /**
     * Not Found: Track not found
     */
    404: unknown;
};

export type TracksPublicControllerLikeTrackResponses = {
    /**
     * Created: User reaction recorded and counters updated
     */
    201: ReactionOutput;
};

export type TracksPublicControllerLikeTrackResponse = TracksPublicControllerLikeTrackResponses[keyof TracksPublicControllerLikeTrackResponses];

export type TracksPublicControllerDislikeTrackData = {
    body?: never;
    path: {
        trackId: string;
    };
    query?: never;
    url: '/playlists/tracks/{trackId}/dislikes';
};

export type TracksPublicControllerDislikeTrackErrors = {
    /**
     * Bad Request: Invalid track ID
     */
    400: unknown;
    /**
     * Unauthorized: User not authenticated
     */
    401: unknown;
    /**
     * Not Found: Track not found
     */
    404: unknown;
};

export type TracksPublicControllerDislikeTrackResponses = {
    /**
     * Created: User reaction recorded and counters updated
     */
    201: ReactionOutput;
};

export type TracksPublicControllerDislikeTrackResponse = TracksPublicControllerDislikeTrackResponses[keyof TracksPublicControllerDislikeTrackResponses];

export type TracksPublicControllerRemoveTrackReactionData = {
    body?: never;
    path: {
        trackId: string;
    };
    query?: never;
    url: '/playlists/tracks/{trackId}/reactions';
};

export type TracksPublicControllerRemoveTrackReactionErrors = {
    /**
     * Unauthorized: User not authenticated
     */
    401: unknown;
};

export type TracksPublicControllerRemoveTrackReactionResponses = {
    /**
     * OK: Reaction removed successfully
     */
    200: ReactionOutput;
};

export type TracksPublicControllerRemoveTrackReactionResponse = TracksPublicControllerRemoveTrackReactionResponses[keyof TracksPublicControllerRemoveTrackReactionResponses];

export type PlaylistsPublicControllerLikePlaylistData = {
    body?: never;
    path: {
        playlistId: string;
    };
    query?: never;
    url: '/playlists/{playlistId}/likes';
};

export type PlaylistsPublicControllerLikePlaylistErrors = {
    /**
     * Bad Request: Invalid playlist ID
     */
    400: unknown;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Not Found: Playlist not found
     */
    404: unknown;
};

export type PlaylistsPublicControllerLikePlaylistResponses = {
    /**
     * Created: Like recorded successfully
     */
    201: ReactionOutput;
};

export type PlaylistsPublicControllerLikePlaylistResponse = PlaylistsPublicControllerLikePlaylistResponses[keyof PlaylistsPublicControllerLikePlaylistResponses];

export type PlaylistsPublicControllerDislikePlaylistData = {
    body?: never;
    path: {
        playlistId: string;
    };
    query?: never;
    url: '/playlists/{playlistId}/dislikes';
};

export type PlaylistsPublicControllerDislikePlaylistErrors = {
    /**
     * Bad Request: Invalid playlist ID
     */
    400: unknown;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Not Found: Playlist not found
     */
    404: unknown;
};

export type PlaylistsPublicControllerDislikePlaylistResponses = {
    /**
     * Created: Dislike recorded successfully
     */
    201: ReactionOutput;
};

export type PlaylistsPublicControllerDislikePlaylistResponse = PlaylistsPublicControllerDislikePlaylistResponses[keyof PlaylistsPublicControllerDislikePlaylistResponses];

export type PlaylistsPublicControllerRemovePlaylistReactionData = {
    body?: never;
    path: {
        playlistId: string;
    };
    query?: never;
    url: '/playlists/{playlistId}/reactions';
};

export type PlaylistsPublicControllerRemovePlaylistReactionErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Not Found: Playlist not found
     */
    404: unknown;
};

export type PlaylistsPublicControllerRemovePlaylistReactionResponses = {
    /**
     * OK: Reaction removed successfully
     */
    200: ReactionOutput;
};

export type PlaylistsPublicControllerRemovePlaylistReactionResponse = PlaylistsPublicControllerRemovePlaylistReactionResponses[keyof PlaylistsPublicControllerRemovePlaylistReactionResponses];

export type TracksControllerReorderTrackData = {
    body: ReorderTracksRequestPayload;
    path: {
        playlistId: string;
        trackId: string;
    };
    query?: never;
    url: '/playlists/{playlistId}/tracks/{trackId}/reorder';
};

export type TracksControllerReorderTrackErrors = {
    /**
     * Bad Request: Cannot place a track after itself
     */
    400: unknown;
    /**
     * Forbidden: No access to the playlist
     */
    403: unknown;
    /**
     * Not Found: Track or putAfterItemId not found
     */
    404: unknown;
};

export type TracksControllerReorderTrackResponses = {
    /**
     * OK: Track order updated successfully
     */
    200: unknown;
};

export type TracksControllerAddTrackToPlaylistData = {
    body: AddTrackToPlaylistRequestPayload;
    path: {
        playlistId: string;
    };
    query?: never;
    url: '/playlists/{playlistId}/relationships/tracks';
};

export type TracksControllerAddTrackToPlaylistErrors = {
    /**
     * Forbidden: No access to the playlist or track limit exceeded (max 10 tracks)
     */
    403: unknown;
    /**
     * Not Found: Playlist not found
     */
    404: unknown;
};

export type TracksControllerAddTrackToPlaylistResponses = {
    /**
     * No Content: Track added to the playlist successfully
     */
    204: void;
};

export type TracksControllerAddTrackToPlaylistResponse = TracksControllerAddTrackToPlaylistResponses[keyof TracksControllerAddTrackToPlaylistResponses];

export type TracksControllerUnbindTrackFromPlaylistData = {
    body?: never;
    path: {
        playlistId: string;
        trackId: string;
    };
    query?: never;
    url: '/playlists/{playlistId}/relationships/tracks/{trackId}';
};

export type TracksControllerUnbindTrackFromPlaylistErrors = {
    /**
     * Forbidden: No access to the playlist
     */
    403: unknown;
    /**
     * Not Found: Playlist not found
     */
    404: unknown;
};

export type TracksControllerUnbindTrackFromPlaylistResponses = {
    /**
     * No Content: Track removed from the playlist
     */
    204: void;
};

export type TracksControllerUnbindTrackFromPlaylistResponse = TracksControllerUnbindTrackFromPlaylistResponses[keyof TracksControllerUnbindTrackFromPlaylistResponses];

export type TracksControllerPublishTrackData = {
    body?: never;
    path: {
        trackId: string;
    };
    query?: never;
    url: '/playlists/tracks/{trackId}/actions/publish';
};

export type TracksControllerPublishTrackErrors = {
    /**
     * Forbidden: Publishing another user’s track is not allowed
     */
    403: unknown;
    /**
     * Not Found: Track with the specified ID not found
     */
    404: unknown;
    /**
     * Conflict: Track is already published
     */
    409: unknown;
};

export type TracksControllerPublishTrackResponses = {
    /**
     * No Content: Track published successfully
     */
    204: void;
};

export type TracksControllerPublishTrackResponse = TracksControllerPublishTrackResponses[keyof TracksControllerPublishTrackResponses];

export type TracksControllerDeleteTrackCoverData = {
    body?: never;
    path: {
        trackId: string;
    };
    query?: never;
    url: '/playlists/tracks/{trackId}/cover';
};

export type TracksControllerDeleteTrackCoverErrors = {
    /**
     * Forbidden: Removing another user's track cover is not allowed
     */
    403: unknown;
    /**
     * Not Found: Track not found
     */
    404: unknown;
};

export type TracksControllerDeleteTrackCoverResponses = {
    /**
     * No Content: Cover deleted successfully
     */
    204: void;
};

export type TracksControllerDeleteTrackCoverResponse = TracksControllerDeleteTrackCoverResponses[keyof TracksControllerDeleteTrackCoverResponses];

export type TracksControllerUploadTrackCoverData = {
    /**
     * Image file:<br/>
     * • Field name — <code>cover</code><br/>
     * • Allowed MIME types — <code>image/jpeg</code>, <code>image/png</code>, <code>image/gif</code><br/>
     * • Maximum size — <code>100 KB</code>
     */
    body: {
        cover: Blob | File;
    };
    path: {
        /**
         * ID of the track for which the cover is being uploaded
         */
        trackId: string;
    };
    query?: never;
    url: '/playlists/tracks/{trackId}/cover';
};

export type TracksControllerUploadTrackCoverErrors = {
    /**
     * Bad Request: Invalid file or size exceeded
     */
    400: unknown;
    /**
     * Forbidden: Cannot upload a cover for another user’s track
     */
    403: unknown;
    /**
     * Not Found: Track not found
     */
    404: unknown;
};

export type TracksControllerUploadTrackCoverResponses = {
    /**
     * OK: Cover uploaded successfully
     */
    200: TrackImages;
};

export type TracksControllerUploadTrackCoverResponse = TracksControllerUploadTrackCoverResponses[keyof TracksControllerUploadTrackCoverResponses];

export type TracksControllerUploadTrackMp3Data = {
    body: {
        title: string;
        file: Blob | File;
    };
    path?: never;
    query?: never;
    url: '/playlists/tracks/upload';
};

export type TracksControllerUploadTrackMp3Errors = {
    /**
     * Bad Request: Invalid file format or file size exceeded
     */
    400: unknown;
    /**
     * Internal Server Error: Error saving file or track
     */
    500: unknown;
};

export type TracksControllerUploadTrackMp3Responses = {
    /**
     * OK: Track created successfully
     */
    200: GetTrackDetailsOutput;
};

export type TracksControllerUploadTrackMp3Response = TracksControllerUploadTrackMp3Responses[keyof TracksControllerUploadTrackMp3Responses];

export type ArtistsControllerCreateArtistData = {
    body: CreateArtistRequestPayload;
    path?: never;
    query?: never;
    url: '/artists';
};

export type ArtistsControllerCreateArtistErrors = {
    /**
     * Bad Request: Validation error or invalid input
     */
    400: unknown;
    /**
     * Unauthorized: User not authenticated
     */
    401: unknown;
    /**
     * Forbidden: Limit of 100 artists per user reached
     */
    403: unknown;
    /**
     * Conflict: Artist with the given name already exists
     */
    409: unknown;
};

export type ArtistsControllerCreateArtistResponses = {
    /**
     * Created: Artist created successfully
     */
    201: ArtistRef;
};

export type ArtistsControllerCreateArtistResponse = ArtistsControllerCreateArtistResponses[keyof ArtistsControllerCreateArtistResponses];

export type ArtistsControllerSearchArtistData = {
    body?: never;
    path?: never;
    query: {
        search: string;
    };
    url: '/artists/search';
};

export type ArtistsControllerSearchArtistResponses = {
    /**
     * OK: List of artists matching the search
     */
    200: Array<ArtistRef>;
};

export type ArtistsControllerSearchArtistResponse = ArtistsControllerSearchArtistResponses[keyof ArtistsControllerSearchArtistResponses];

export type ArtistsControllerDeleteArtistData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/artists/{id}';
};

export type ArtistsControllerDeleteArtistErrors = {
    /**
     * Forbidden: Artist is attached to tracks or was created by another user
     */
    403: unknown;
    /**
     * Not Found: Artist with the specified ID not found
     */
    404: unknown;
};

export type ArtistsControllerDeleteArtistResponses = {
    /**
     * No Content: Artist deleted successfully
     */
    204: void;
};

export type ArtistsControllerDeleteArtistResponse = ArtistsControllerDeleteArtistResponses[keyof ArtistsControllerDeleteArtistResponses];

export type AuthControllerOauthRedirectData = {
    body?: never;
    path?: never;
    query: {
        /**
         * The callback URL to redirect after grand access,
         * https://oauth.apihub.it-incubator.io/realms/apihub/protocol/openid-connect/auth?client_id=musicfun&response_type=code&redirect_uri=http://localhost:3000/oauth2/callback&scope=openid
         */
        callbackUrl: string;
    };
    url: '/auth/oauth-redirect';
};

export type AuthControllerOauthRedirectResponses = {
    /**
     * OK: Redirect executed successfully
     */
    200: unknown;
};

export type AuthControllerLoginData = {
    body: LoginRequestPayload;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type AuthControllerLoginErrors = {
    /**
     * Bad Request: Invalid request format or required parameters are missing
     */
    400: BadRequestException;
    /**
     * Unauthorized: Code is invalid, expired, missing, or redirectUri does not match
     */
    401: UnauthorizedException;
};

export type AuthControllerLoginError = AuthControllerLoginErrors[keyof AuthControllerLoginErrors];

export type AuthControllerLoginResponses = {
    /**
     * OK: Token pair retrieved successfully
     */
    200: RefreshOutput;
};

export type AuthControllerLoginResponse = AuthControllerLoginResponses[keyof AuthControllerLoginResponses];

export type AuthControllerRefreshData = {
    body: RefreshRequestPayload;
    path?: never;
    query?: never;
    url: '/auth/refresh';
};

export type AuthControllerRefreshErrors = {
    /**
     * Unauthorized: Refresh token is invalid, expired, or missing
     */
    401: UnauthorizedException;
};

export type AuthControllerRefreshError = AuthControllerRefreshErrors[keyof AuthControllerRefreshErrors];

export type AuthControllerRefreshResponses = {
    /**
     * OK: Token pair refreshed successfully
     */
    200: RefreshOutput;
};

export type AuthControllerRefreshResponse = AuthControllerRefreshResponses[keyof AuthControllerRefreshResponses];

export type AuthControllerLogoutData = {
    body: LogoutRequestPayload;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type AuthControllerLogoutResponses = {
    /**
     * No Content: Refresh token deactivated; access token remains valid.
     */
    204: void;
};

export type AuthControllerLogoutResponse = AuthControllerLogoutResponses[keyof AuthControllerLogoutResponses];

export type AuthControllerGetMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/me';
};

export type AuthControllerGetMeErrors = {
    /**
     * Unauthorized: access token is missing or invalid
     */
    401: unknown;
};

export type AuthControllerGetMeResponses = {
    /**
     * OK: Successfully retrieved user information
     */
    200: GetMeOutput;
};

export type AuthControllerGetMeResponse = AuthControllerGetMeResponses[keyof AuthControllerGetMeResponses];

export type SimpleAuthControllerLoginData = {
    body: SimpleLoginRequestPayload;
    path?: never;
    query?: never;
    url: '/auth/simple/login';
};

export type SimpleAuthControllerLoginErrors = {
    /**
     * Unauthorized: Invalid login or password
     */
    401: UnauthorizedException;
};

export type SimpleAuthControllerLoginError = SimpleAuthControllerLoginErrors[keyof SimpleAuthControllerLoginErrors];

export type SimpleAuthControllerLoginResponses = {
    /**
     * OK: Token pair retrieved successfully
     */
    200: SimpleLoginOutput;
};

export type SimpleAuthControllerLoginResponse = SimpleAuthControllerLoginResponses[keyof SimpleAuthControllerLoginResponses];

export type SimpleAuthControllerRefreshData = {
    body: SimpleRefreshRequestPayload;
    path?: never;
    query?: never;
    url: '/auth/simple/refresh';
};

export type SimpleAuthControllerRefreshErrors = {
    /**
     * Unauthorized: Refresh token is invalid, expired, or revoked
     */
    401: UnauthorizedException;
};

export type SimpleAuthControllerRefreshError = SimpleAuthControllerRefreshErrors[keyof SimpleAuthControllerRefreshErrors];

export type SimpleAuthControllerRefreshResponses = {
    /**
     * OK: Token pair refreshed successfully
     */
    200: SimpleLoginOutput;
};

export type SimpleAuthControllerRefreshResponse = SimpleAuthControllerRefreshResponses[keyof SimpleAuthControllerRefreshResponses];

export type SimpleAuthControllerLogoutData = {
    body: SimpleLogoutRequestPayload;
    path?: never;
    query?: never;
    url: '/auth/simple/logout';
};

export type SimpleAuthControllerLogoutResponses = {
    /**
     * No Content: Refresh token has been revoked
     */
    204: void;
};

export type SimpleAuthControllerLogoutResponse = SimpleAuthControllerLogoutResponses[keyof SimpleAuthControllerLogoutResponses];

export type TagsControllerCreateTagData = {
    body: CreateTagRequestPayload;
    path?: never;
    query?: never;
    url: '/tags';
};

export type TagsControllerCreateTagErrors = {
    /**
     * Bad Request: Validation error
     */
    400: unknown;
    /**
     * Unauthorized: User not authenticated
     */
    401: unknown;
    /**
     * Forbidden: Limit of 100 tags per user reached
     */
    403: unknown;
    /**
     * Conflict: Tag with the given name already exists
     */
    409: unknown;
};

export type TagsControllerCreateTagResponses = {
    /**
     * Created: Tag created successfully
     */
    201: GetTagOutput;
};

export type TagsControllerCreateTagResponse = TagsControllerCreateTagResponses[keyof TagsControllerCreateTagResponses];

export type TagsControllerSearchTagsData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Substring to search tags by (using normalized name)
         */
        search: string;
    };
    url: '/tags/search';
};

export type TagsControllerSearchTagsErrors = {
    /**
     * Bad Request: Invalid search query
     */
    400: unknown;
};

export type TagsControllerSearchTagsResponses = {
    /**
     * OK: List of matching tags
     */
    200: GetTagsOutput;
};

export type TagsControllerSearchTagsResponse = TagsControllerSearchTagsResponses[keyof TagsControllerSearchTagsResponses];

export type TagsControllerDeleteTagData = {
    body?: never;
    path: {
        /**
         * ID of the tag to delete
         */
        id: string;
    };
    query?: never;
    url: '/tags/{id}';
};

export type TagsControllerDeleteTagErrors = {
    /**
     * Unauthorized: User not authenticated
     */
    401: unknown;
    /**
     * Forbidden: Tag was created by another user or is attached to tracks or playlists
     */
    403: unknown;
    /**
     * Not Found: Tag with the specified ID not found
     */
    404: unknown;
};

export type TagsControllerDeleteTagResponses = {
    /**
     * No Content: Tag deleted successfully
     */
    204: void;
};

export type TagsControllerDeleteTagResponse = TagsControllerDeleteTagResponses[keyof TagsControllerDeleteTagResponses];
